INSERT into safetytips (title, body, createdAt, updatedAt) VALUES ("Be Alert", "Always be alert and aware of the people around you.", NOW(), NOW());
INSERT into safetytips (title, body, createdAt, updatedAt) VALUES ("Prevention", "Educate yourself concerning prevention tactics.", NOW(), NOW());
INSERT into safetytips (title, body, createdAt, updatedAt) VALUES ("Be Aware", "Be aware of locations and situations which would make you appear vulnerable to crime, such as alleys and dark parking lots.", NOW(), NOW());
INSERT into safetytips (title, body, createdAt, updatedAt) VALUES ("Be Alert", "Be alert to your surroundings and the people around you—especially if you are alone or it is dark.", NOW(), NOW());
INSERT into safetytips (title, body, createdAt, updatedAt) VALUES ("Stronger Together", "Whenever possible, travel with a friend.", NOW(), NOW());
INSERT into safetytips (title, body, createdAt, updatedAt) VALUES ("Stay in the Light", "Stay in well-lighted areas as much as possible.", NOW(), NOW());
INSERT into safetytips (title, body, createdAt, updatedAt) VALUES ("Stay Clear", "Walk close to the curb. Avoid doorways, bushes and alleys where someone could hide.", NOW(), NOW());
INSERT into safetytips (title, body, createdAt, updatedAt) VALUES ("Distractions Kill", "Do not use or wear anything that will impede your vision or hearing (i.e. iPods).", NOW(), NOW());
INSERT into safetytips (title, body, createdAt, updatedAt) VALUES ("Keep Walking", "Do not respond to conversation from strangers on the street—continue walking.", NOW(), NOW());
INSERT into safetytips (title, body, createdAt, updatedAt) VALUES ("Eye Contact", "Make eye contact with people when walking.", NOW(), NOW());
INSERT into safetytips (title, body, createdAt, updatedAt) VALUES ("Confidence", "Walk confidently at a steady pace.", NOW(), NOW());
INSERT into safetytips (title, body, createdAt, updatedAt) VALUES ("Purse Safety", "If you carry a purse, carry it securely between your arm and your body. Although a purse-snatcher's intent is to steal the purse, your personal safety may depend on not clinging to it.", NOW(), NOW());
INSERT into safetytips (title, body, createdAt, updatedAt) VALUES ("Lock It", "Always lock your car doors after entering or leaving your vehicle.", NOW(), NOW());
INSERT into safetytips (title, body, createdAt, updatedAt) VALUES ("Parking", "Park in well-lighted areas.", NOW(), NOW());
INSERT into safetytips (title, body, createdAt, updatedAt) VALUES ("Keys", "Have your car keys in your hand so you don't have to linger before entering your car.", NOW(), NOW());
INSERT into safetytips (title, body, createdAt, updatedAt) VALUES ("Look First", "Check the interior of your vehicle for intruders before entering your car.", NOW(), NOW());
INSERT into safetytips (title, body, createdAt, updatedAt) VALUES ("Find a cop", "If you think you are being followed, drive to a public place or a police or sheriff station.", NOW(), NOW());
INSERT into safetytips (title, body, createdAt, updatedAt) VALUES ("Flag Them Down", "If your car breaks down, open the hood and attach a white cloth to the car antennae. If someone stops to help, stay in your locked car and ask them to call the police, sheriff or a tow truck service.", NOW(), NOW());
INSERT into safetytips (title, body, createdAt, updatedAt) VALUES ("Don't stop", "Don't stop to aid motorists by the side of the road. Make a phone call requesting help for them.", NOW(), NOW());
INSERT into safetytips (title, body, createdAt, updatedAt) VALUES ("Taking the Bus", "Try to avoid isolated bus stops.", NOW(), NOW());
INSERT into safetytips (title, body, createdAt, updatedAt) VALUES ("Money on Display", "Don't open your purse or wallet while boarding the bus—have your pass or money already in your hand.", NOW(), NOW());
INSERT into safetytips (title, body, createdAt, updatedAt) VALUES ("Shiny Things", "Keep jewelry out of sight; don't flash jewelry; turn rings around so the stones don't show.", NOW(), NOW());
INSERT into safetytips (title, body, createdAt, updatedAt) VALUES ("Pockets", "Be alert to pickpocketers on crowded buses; check your purse or wallet if someone is jostling, crowding or pushing you.", NOW(), NOW());
INSERT into safetytips (title, body, createdAt, updatedAt) VALUES ("In the Front", "Keep your belongings in front of you and hold close to your body with both hands.", NOW(), NOW());
