INSERT into safetyNote (title, body) VALUES ("Be Alert", "Always be alert and aware of the people around you.");
INSERT into safetyNote (title, body) VALUES ("Prevention", "Educate yourself concerning prevention tactics.");
INSERT into safetyNote (title, body) VALUES ("Be Aware", "Be aware of locations and situations which would make you appear vulnerable to crime, such as alleys and dark parking lots.");
INSERT into safetyNote (title, body) VALUES ("Be Alert", "Be alert to your surroundings and the people around you—especially if you are alone or it is dark.");
INSERT into safetyNote (title, body) VALUES ("Stronger Together", "Whenever possible, travel with a friend.");
INSERT into safetyNote (title, body) VALUES ("Stay in the Light", "Stay in well-lighted areas as much as possible.");
INSERT into safetyNote (title, body) VALUES ("Stay Clear", "Walk close to the curb. Avoid doorways, bushes and alleys where someone could hide.");
INSERT into safetyNote (title, body) VALUES ("Distractions Kill", "Do not use or wear anything that will impede your vision or hearing (i.e. iPods).");
INSERT into safetyNote (title, body) VALUES ("Keep Walking", "Do not respond to conversation from strangers on the street—continue walking.");
INSERT into safetyNote (title, body) VALUES ("Eye Contact", "Make eye contact with people when walking.");
INSERT into safetyNote (title, body) VALUES ("Confidence", "Walk confidently at a steady pace.");
INSERT into safetyNote (title, body) VALUES ("Purse Safety", "If you carry a purse, carry it securely between your arm and your body. Although a purse-snatcher's intent is to steal the purse, your personal safety may depend on not clinging to it.");
INSERT into safetyNote (title, body) VALUES ("Lock It", "Always lock your car doors after entering or leaving your vehicle.");
INSERT into safetyNote (title, body) VALUES ("Parking", "Park in well-lighted areas.");
INSERT into safetyNote (title, body) VALUES ("Keys", "Have your car keys in your hand so you don't have to linger before entering your car.");
INSERT into safetyNote (title, body) VALUES ("Look First", "Check the interior of your vehicle for intruders before entering your car.");
INSERT into safetyNote (title, body) VALUES ("Find a cop", "If you think you are being followed, drive to a public place or a police or sheriff station.");
INSERT into safetyNote (title, body) VALUES ("Flag Them Down", "If your car breaks down, open the hood and attach a white cloth to the car antennae. If someone stops to help, stay in your locked car and ask them to call the police, sheriff or a tow truck service.");
INSERT into safetyNote (title, body) VALUES ("Don't stop", "Don't stop to aid motorists by the side of the road. Make a phone call requesting help for them.");
INSERT into safetyNote (title, body) VALUES ("Taking the Bus", "Try to avoid isolated bus stops.");
INSERT into safetyNote (title, body) VALUES ("Money on Display", "Don't open your purse or wallet while boarding the bus—have your pass or money already in your hand.");
INSERT into safetyNote (title, body) VALUES ("Shiny Things", "Keep jewelry out of sight; don't flash jewelry; turn rings around so the stones don't show.");
INSERT into safetyNote (title, body) VALUES ("Pockets", "Be alert to pickpocketers on crowded buses; check your purse or wallet if someone is jostling, crowding or pushing you.");
INSERT into safetyNote (title, body) VALUES ("In the Front", "Keep your belongings in front of you and hold close to your body with both hands.");
