INSERT into userReport (category, date, streetAddress, city, state, zip, description) VALUES ("auto theft","2021-02-01", "828 S BROADWAY ST", "Denver","Colorado","80211","My neighbor's girlfriend stole his car.");
INSERT into userReport (category, date, streetAddress, city, state, zip, description) VALUES ("aggrevated assault","2021-02-01", "8298 E NORTHFIELD BLVD", "Denver", "Colorado", "80238", "My sister's boyfriend came home drunk and beat her.","2021-02-02","");
INSERT into userReport (category, date, streetAddress, city, state, zip, description) VALUES ("all other crimes", "2021-02-02", "6200 E COLFAX AVE", "Denver", "Colorado", "80220", "My landlord won't return my deposit even though I left my apartment in better shape than I found it.");
INSERT into userReport (category, date, streetAddress, city, state, zip, description) VALUES ("arson", "2021-02-03", "500 BLK S FEDERAL BLVD", "Denver", "Colorado", "80219", "My upstairs neighbor told me last month that he was planning on setting his apartment on fire to collect the insurance money. I thought he was joking, but then he actually did it today!");
INSERT into userReport (category, date, streetAddress, city, state, zip, description) VALUES ("burglary", "2021-02-04", "7401 E 26TH AVE", "Denver", "Colorado", "80238", "I came home from work and noticed my door was open. When I went in I found out that someone stole my tv, x-box and all the loose change.");
INSERT into userReport (category, date, streetAddress, city, state, zip, description) VALUES ("theft", "2021-02-04", "2500 WALNUT ST", "Denver", "Colorado", "80205", "Some guy stole my purse and ran away. I have never seen him before, but he knew me.");
INSERT into userReport (category, date, streetAddress, city, state, zip, description) VALUES ("drug or alcohol", "2021-02-05", "3700 BLOCK N MARIPOSA ST", "Denver", "Colorado", "80211", "I was driving my the park and noticed a bunch of teenagers drinking beer. They seemed pretty sloshed. I called the police dept to report it as well as use this wonderfully amazing app!");
INSERT into userReport (category, date, streetAddress, city, state, zip, description) VALUES ("drug or alcohol", "2021-02-05", "699 W 29TH AVE", "Denver", "Colorado", "80202", "While playing softball with some of my buddies from work I noticed John Doe was not able to stay awake...even while standing. At first, I thought maybe he had too much fun last night. But then, I noticed how bad he smelled-very chemical like drano. I'm thinking this may be meth!");
INSERT into userReport (category, date, streetAddress, city, state, zip, description) VALUES ("larceny", "2021-02-06", "1724 N IRVING ST",  "Denver", "Colorado", "80204", "Some dude came into my backyard and stole my brand new trampoline. I couldn't quite see him because it was dark, but he was STRONG. I reported this to the police. Watch out neighbors.");
INSERT into userReport (category, date, streetAddress, city, state, zip, description) VALUES ("murder", "2021-02-06", "1701 N HIGH ST",  "Denver", "Colorado", "80218", "I'm pretty sure my neighbor's dog murdered the mailman. Max chased that man for at least 2 blocks. Haven't seem the mailman since.");
INSERT into userReport (category, date, streetAddress, city, state, zip, description) VALUES ("other crimes against persons", "2021-02-07", "5501 E 47TH AVE", "Denver", "Colorado", "80216", "My coworker wears the most awful perfume. This must be a crime against humanity.");
INSERT into userReport (category, date, streetAddress, city, state, zip, description) VALUES ("public disorder", "2021-02-07", "21353 E 50TH PL", "Denver", "Colorado", "80249", "As part of a punishment, my parents are making me report my party when they were out of town. I learned my lesson....not.");
INSERT into userReport (category, date, streetAddress, city, state, zip, description) VALUES ("robbery", "2021-02-07", "5275 E 39TH AVE", "Denver", "Colorado", "80207", "Chris sneaked up on John, demanding John's money while pressing a plastic object into his back, and John gave up his wallet.");
INSERT into userReport (category, date, streetAddress, city, state, zip, description) VALUES ("sexual assault", "2021-02-08", "1300 BLOCK N WASHINGTON ST", "Denver", "Colorado", "80203", "My boyfriend keeps grabbing my butt at the most innapropriate times. I have told him to stop, but he won't, so I'm breaking up with him. Ladies- watch out for Joe Shmow.");
INSERT into userReport (category, date, streetAddress, city, state, zip, description) VALUES ("theft from motor vehicle", "2021-02-08", "E SPEER BLVD / N WASHINGTON ST", "Denver", "Colorado", "80203", "I went on a vacation with my sister and when I came back I found my car broken into and my stereo was gone.");
INSERT into userReport (category, date, streetAddress, city, state, zip, description) VALUES ("traffic accident", "2021-02-09", "3900 BLK N COLORADO BLVD", "Denver", "Colorado", "80216", "I was minding my own business and some jerk swerved into my lane. He didn't stop. Now the whole side of my car is messed up.");
INSERT into userReport (category, date, streetAddress, city, state, zip, description) VALUES ("white collar crime", "2021-02-09", "11400 BLK E 53RD AVE", "Denver", "Colorado", "80239", "I don't want to talk about it.");
INSERT into userReport (category, date, streetAddress, city, state, zip, description) VALUES ("robbery", "2021-02-10", "1065 S QUIVAS ST", "Denver", "Colorado", "80223", "I was using an atm and some kid just grabbed my purse.");
INSERT into userReport (category, date, streetAddress, city, state, zip, description) VALUES ("theft from motor vehicle", "2021-02-10", "1600 BLK S UNIVERSITY BLVD", "Denver", "Colorado", "80210", "I woke up to my car alarm going off. I chased the kid off, but I thought I'd report it here anyway.");
INSERT into userReport (category, date, streetAddress, city, state, zip, description) VALUES ("burglary", "2021-02-10", "N CENTRAL PARK BLVD / E 47TH AVE", "Denver", "Colorado", "80238", "Our business was robbed. Someone broke in and stole all the computers, printers and fax machines.");


select * from userReport